# Generated by Django 3.1.5 on 2021-01-24 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 24, 14, 47, 20, 107540)),
        ),
    ]
