# Generated by Django 3.1.5 on 2021-01-27 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210125_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 27, 15, 7, 45, 321833)),
        ),
    ]
