# Generated by Django 3.1.5 on 2021-01-27 13:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210127_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 27, 16, 15, 9, 540811)),
        ),
    ]
